# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFzNLP2Vknf0MBQ4DCms2C5E_rsKVB-v
"""

import yfinance as yf
import pandas as pd
import numpy as np
from neuralprophet import NeuralProphet
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
import math
from pmdarima import auto_arima
import shap
import torch

df = yf.download("AAPL", start="2018-01-01", end="2023-01-01")
data = df[["Close"]].reset_index()
data.rename(columns={"Date": "ds", "Close": "y"}, inplace=True)

train_size = int(len(data) * 0.8)
train = data[:train_size]
test = data[train_size:]

model = NeuralProphet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    n_lags=30,
    n_forecasts=1,
    learning_rate=0.01,
    epochs=50,
)

model.fit(train, freq="D")

future = model.make_future_dataframe(train, periods=len(test))
forecast = model.predict(future)

pred = forecast["yhat1"].iloc[-len(test):].values
actual = test["y"].values

mae = mean_absolute_error(actual, pred)
rmse = math.sqrt(mean_squared_error(actual, pred))

print("Neural Prophet MAE:", mae)
print("Neural Prophet RMSE:", rmse)

arima = auto_arima(train["y"], seasonal=False, trace=False, suppress_warnings=True)
arima_pred = arima.predict(n_periods=len(test))

arima_mae = mean_absolute_error(actual, arima_pred)
arima_rmse = math.sqrt(mean_squared_error(actual, arima_pred))

print("ARIMA MAE:", arima_mae)
print("ARIMA RMSE:", arima_rmse)

df_lagged = model._create_training_data(train)[0]
X = torch.tensor(df_lagged["X"].astype(np.float32))

background = X[:200]
explainer = shap.DeepExplainer(model.model, background)
shap_values = explainer.shap_values(X[:200])

shap.summary_plot(shap_values, X[:200])
shap.summary_plot(shap_values, X[:200], plot_type="bar")

